# 基础镜像
FROM openjdk:8-jre

# 设置环境变量
ENV TZ=Asia/Shanghai
# 通过符号链接将系统时区设置为之前定义的 TZ 环境变量所指定的时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 创建数据卷 数据卷可以用于在容器和主机之间共享数据，或者在多个容器之间共享数据，方便数据的持久化和管理
VOLUME /app/project/config

# 复制主机的jar包到容器中的应用目录
COPY ./target/config-server.jar /app/project/config/config-server.jar

# 设置工作目录 后续的命令（如 ENTRYPOINT 或 CMD 中执行的命令）将在这个目录下执行，方便定位和操作相关文件
WORKDIR /app/project/config

# 容器启动执行命令
ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-jar", "config-server.jar"]

# 暴露端口号
EXPOSE 8762